name: Android CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build debug APK and run JVM tests
        run: |
          ./gradlew assembleDebug lintDebug testDebugUnitTest --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PersianCalendar
          path: PersianCalendar/build/outputs/apk/**/*.apk

      - name: Archive reports for failed build
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: "*/build/reports"

  # test-android:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       api-level: [29]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: 21
  #         distribution: temurin

  #     - uses: gradle/actions/setup-gradle@v4

  #     # https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/
  #     - name: Enable KVM group perms
  #       run: |
  #         echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
  #         sudo udevadm control --reload-rules
  #         sudo udevadm trigger --name-match=kvm
  #         ls /dev/kvm

  #     - name: Run Android tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: ${{ matrix.api-level }}
  #         script: ./gradlew connectedDebugAndroidTest --info --full-stacktrace

  #     - name: Upload results
  #       if: ${{ always() }}
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: instrumentation-test-results ${{ matrix.api-level }}
  #         path: ./**/build/reports/androidTests/connected/**
